
## PLEASE WRITE VALUES WITH DECIMAL POINT >>  2.0 NOT 2 ####
pendulum_parameters: 
  ros__parameters:
    mass: 3.0                       # kg

    initial_angle: -3.0            # rad

    initial_angular_speed: 0.0      # rad/s

    length: 2.0                     # m

    gravity: 9.8                    # m/s2

    water_speed: -3.0               # m/s

    water_density: 1000.0           # kg/m3

    pendulum_radius: 0.08           # m

    drag_coefficient: 1.0     
  

